import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	private static final Logger LOGGER = LoggerFactory.getLogger(Library.class);
	
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
    	LOGGER.info("test!!");
	}
}
